### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by timoon** [kkaempf/tffs#2]
Hi,

I still have full HDD with Topfield recordings and want to access these with the tffs driver. I was unable to compile it either way. With gcc-4.8.5 I get the same error as with recent gcc-10.1:

src/main.cpp:169:18: error: invalid conversion from ‘int (*)(const char*, fuse_file_info*)’ to ‘int (*)(const char*, int)’ [-fpermissive]
   tffs_oper.open = tffs_open;

gcc-4.7 throws another error and the gcc-4.8.4 source itself fails to compile. Could you give me a little hint? Unfortunately I am not very familiar with changing the source code to make it work. Thank you very much in advance

**Comment by kkaempf** [comment]
Please pull from master and try again. It compiles with gcc 10.x here. I don't have any Topfield disk image to test. Use at your own risk.

**Comment by timoon** [comment]
Thank you very much, it seems like the real problem lies somewhere else on my machine... it complains about fuse in the old and the new github version:

src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:169:13: error: ‘struct fuse_operations_compat2’ has no member named ‘readdir’
  169 |   tffs_oper.readdir = tffs_readdir;

I tried to play with #define FUSE_USE_VERSION but it always runs into this error and my knowledge is too limited on this :-(

**Comment by kkaempf** [comment]
Hmm, which version of fuse do you have ? Mine is `2.9.8`. What is your target system ? MacOS or Linux ? Which version ?

**Comment by timoon** [comment]
I am using Archlinux and the library packages extra/fuse2 2.9.9-4 and extra/fuse3 3.9.2-1 are both installed. For some reason it is going down to a fuse version that "uses" fuse_operations_compat2 from fuse_compat.h which does not define "readdir" although there are many other structs like fuse_operations_compat22 or fuse_operations_compat25 which define "readdir".

**Comment by kkaempf** [comment]
Might be that it picks up fuse3 instead of fuse2 :thinking: 
Can you de-install fuse3 and try again ?

**Comment by timoon** [comment]
That did not help, it chooses fuse2. But I had success :-) it was my fault, I had to #define FUSE_USE_VERSION before include fuse.h and I defined 22 and it compiled without error. I mounted the Topfield HDD and could watch the .rec files on it.
